

# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

exec-once = waybar
exec-once = quickshell
exec-once = awww-daemon
exec-once = dunst

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, wofi --show drun
bind = $mainMod, F12, exec, ~/.config/hypr/gamemode.sh
bind = $mainMod, W, exec, waypaper

# Monitor Setup
source = ~/.config/hypr/monitors.conf

# Workspaces config
source = ~/.config/hypr/workspaces.conf

input {
	kb_layout = dk
}
