# Void glow yazi behavior

[mgr]
ratio   = [1, 3, 4]
sort_by = "natural"
sort_dir_first = true
show_hidden = false
linemode  = "size"


[preview]
max_width = 1000
max_height = 1000

[opener]
edit = [
  { run = 'nvim "$@"', block = true }
]
