# Void glow - waypaper config
# GUI wallpaper picker. Backend: awww


[Settings]
language = en
folder = $HOME/Pictures/wallpapers
backend = awww
fill = Fill
sort = name
color = #0d0d0f
subfolders = True
all_subfolders = False
show_hidden = False
show_gifs_only = False
post_command = 
number_of_columns = 3
swww_transition_type = grow
swww_transition_step = 90
swww_transition_duration = 1
swww_transition_fps = 60
swww_transition_angle = 0
swww_transition_pos = 0.854,0.989
monitors = All
